### ISSUE TITLE
troll

### ISSUE THREAD

**Issue by Ender-0001** [NeoniteDev/Osmium#1]
https://github.com/NeoniteDev/Osmium/blob/e52b2bd1e2288fa6a15b12519b11cce56d36f9b7/Osmium/constants.h#L42

**Comment by Milxnor** [comment]
> https://github.com/NeoniteDev/Osmium/blob/e52b2bd1e2288fa6a15b12519b11cce56d36f9b7/Osmium/constants.h#L42

darkbladeeu exists
