### ISSUE TITLE
troll

### ISSUE THREAD

**Issue by stormzyidk** [NeoniteDev/Osmium#2]
Stop open sourcing everything and then getting mad people skid ur shit. Fucking r*tards. Ur probably also open sourcing because nobody uses ur shit.

**Comment by Milxnor** [comment]
> Stop open sourcing everything and then getting mad people skid ur shit. Fucking r*tards. Ur probably also open sourcing because nobody uses ur shit.

1. this is for learning purposes
2. no..

**Comment by Fischsalat** [comment]
LMFAOOO

**Comment by AlexDev404** [comment]
> Stop open sourcing everything and then getting mad people skid ur shit. Fucking r*tards. Ur probably also open sourcing because nobody uses ur shit.
@stormzyidk 

Hey stfu you idiot. You don't even know half of the sh*t that's going on here. You don't even know what's going on in your own project StormFN cause u stole it LMFAOOOOOO
